### ISSUE TITLE
Wrong Time

### ISSUE THREAD

**Issue by Sawair** [Toumash/toumash.dailystatus#1]
Time is smaller than sum of last 17 days (it's 17.03 and my "This Month" is 83h, about 30 hours more than showed on app). 
![obraz](https://user-images.githubusercontent.com/18036211/37554335-427bb31c-29d7-11e8-92c0-a17a0ef84cd4.png)

**Comment by Sawair** [comment]
Here you have fix: #2

**Comment by Toumash** [comment]
#2 fixes this bug
